import express from 'express';
import { adminBlogs, adminCategories, adminInquiries, adminProjects, adminTestimonials, adminUsers, getCourse, getSettings, stats, updateCourse, updateSettings } from '../controllers/adminController.js';
import { protect, restrictTo } from '../middleware/authMiddleware.js';
const router = express.Router();
router.use(protect, restrictTo('admin', 'staff'));
router.get('/stats', stats);
router.route('/projects').get(adminProjects.list).post(adminProjects.create);
router.route('/projects/:id').get(adminProjects.get).put(adminProjects.update).delete(adminProjects.remove);
router.patch('/projects/:id/status', adminProjects.status);
router.patch('/projects/:id/featured', adminProjects.featured);
router.route('/categories').get(adminCategories.list).post(adminCategories.create);
router.route('/categories/:id').get(adminCategories.get).put(adminCategories.update).delete(adminCategories.remove);
router.route('/inquiries').get(adminInquiries.list);
router.route('/inquiries/:id').get(adminInquiries.get).put(adminInquiries.update).delete(adminInquiries.remove);
router.route('/blogs').get(adminBlogs.list).post(adminBlogs.create);
router.route('/blogs/:id').get(adminBlogs.get).put(adminBlogs.update).delete(adminBlogs.remove);
router.patch('/blogs/:id/status', adminBlogs.status);
router.route('/testimonials').get(adminTestimonials.list).post(adminTestimonials.create);
router.route('/testimonials/:id').get(adminTestimonials.get).put(adminTestimonials.update).delete(adminTestimonials.remove);
router.route('/course').get(getCourse).put(updateCourse);
router.route('/settings').get(getSettings).put(updateSettings);
router.route('/users').get(restrictTo('admin'), adminUsers.list).post(restrictTo('admin'), adminUsers.create);
router.route('/users/:id').put(restrictTo('admin'), adminUsers.update).delete(restrictTo('admin'), adminUsers.remove);
export default router;
