import express from 'express';
import { body } from 'express-validator';
import { optionalAuth } from './shared.js';
import { blogBySlug, categories, course, createInquiry, featuredProjects, listBlogs, listProjects, projectBySlug, relatedBlogs, relatedProjects, siteSettings, testimonials } from '../controllers/publicController.js';
import { validate } from '../middleware/validate.js';
const router = express.Router();
router.get('/projects', listProjects);
router.get('/projects/featured', featuredProjects);
router.get('/projects/:slug', projectBySlug);
router.get('/projects/:slug/related', relatedProjects);
router.get('/categories', categories);
router.get('/blogs', listBlogs);
router.get('/blogs/:slug', blogBySlug);
router.get('/blogs/:slug/related', relatedBlogs);
router.get('/testimonials', testimonials);
router.get('/course', course);
router.get('/site-settings', siteSettings);
router.post('/inquiries', optionalAuth, [body('name').notEmpty().withMessage('Name is required'), body('email').isEmail().withMessage('Valid email required'), body('phone').notEmpty().withMessage('WhatsApp number is required'), body('message').notEmpty().withMessage('Message is required')], validate, createInquiry);
export default router;
